# Generated by Django 2.1.7 on 2019-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('vmserver', '虚拟机'), ('container', '容器')], default='server', max_length=100, verbose_name='asset_type')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='资产编号')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备序列号')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='购买时间')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='过保修期')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='制造商')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='供货商')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产型号')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='状态')),
                ('put_zone', models.SmallIntegerField(blank=True, null=True, verbose_name='放置区域')),
                ('group', models.SmallIntegerField(blank=True, null=True, verbose_name='使用组')),
                ('business', models.SmallIntegerField(blank=True, null=True, verbose_name='业务类型')),
                ('project', models.SmallIntegerField(blank=True, null=True, verbose_name='项目类型')),
                ('mark', models.TextField(blank=True, null=True, verbose_name='资产标示')),
                ('cabinet', models.SmallIntegerField(blank=True, null=True, verbose_name='机柜位置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encode_password', models.CharField(max_length=100, unique=True, verbose_name='encode_password')),
                ('encode_private_key', models.TextField(blank=True, null=True, verbose_name='encode_private_key')),
                ('encode_public_key', models.TextField(blank=True, null=True, verbose_name='encode_public_key')),
                ('random_base64', models.TextField(blank=True, null=True, verbose_name='encode_public_key')),
                ('comment', models.CharField(max_length=300, verbose_name='comment')),
            ],
        ),
    ]
