# Generated by Django 2.1.7 on 2019-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore',
            name='encode_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='encode_password'),
        ),
        migrations.AlterField(
            model_name='keystore',
            name='random_base64',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='random_base64'),
        ),
    ]
