# Generated by Django 2.1.7 on 2019-04-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('link_name', models.CharField(max_length=80, unique=True, verbose_name='link_name')),
                ('is_topmenu', models.BooleanField(default=False, verbose_name='is_topmenu')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='users.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
