# Generated by Django 2.1.7 on 2019-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190407_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link_name',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='link_name'),
        ),
    ]
