# Generated by Django 2.1.7 on 2019-04-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190407_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='link_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='url'),
        ),
    ]
