# Generated by Django 2.1.7 on 2019-04-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190408_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='level',
            field=models.IntegerField(choices=[(1, '一级权限'), (2, '二级权限'), (3, '三级权限')], default=1, verbose_name='level'),
        ),
    ]
