# Generated by Django 2.1.7 on 2019-04-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='parent_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpermissons', to='users.Permission'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], default=1, verbose_name='level'),
        ),
    ]
