# Generated by Django 2.1.7 on 2019-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190408_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='codename'),
        ),
    ]
