# Generated by Django 2.1.7 on 2019-04-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190408_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='seq',
            field=models.IntegerField(default=0, verbose_name='seq'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.IntegerField(choices=[(1, '一级'), (2, '二级')], default=1, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpermissions', to='users.Permission'),
        ),
    ]
