# Generated by Django 2.1.7 on 2019-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190408_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon_name',
            field=models.CharField(blank=True, default='file', max_length=20, null=True, verbose_name='icon_name'),
        ),
    ]
