# Generated by Django 2.1.7 on 2019-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190412_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='role',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='department',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='权限代码'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='权限名'),
        ),
    ]
